ADMIN-PERM: "menosia.admin"
PREFIX: "§f§lMenosia§c§lMC §7» §f"

COMBATTAG-TIMER: 30 #en secondes
COMBATTAG-ATTACKER-MESSAGE: "§fVous venez de frapper §c%player%§f, vous êtes donc en §ccombat§f."
COMBATTAG-VICTIM-MESSAGE: "§fVous venez d'être frappé par §c%player%§f, vous êtes donc en §ccombat§f."

TELEPORTATION-MESSAGE: "§fVous allez être §ctéléporté§f dans §c%tp% §fsecondes."
TELEPORTATION-TIMER: 5 #en secondes
TELEPORTATION-CANCEL: "§fTéléportation §cannulé§f car vous avez §cbougé§f."

#Tu peux en ajouter autant que tu le souhaites en suivant le schema
AUTOMESSAGE:
  - "test"
  - "test2"
  - "test3"
AUTOMESSAGE-TIMER: 180 #temps entre chaque message en seconde

NOLOSELEVEL-PERM: "menosia.nolosexp"
ACHAT-EFFECTUE: "§fAchat effectué avec §asuccès§f."
ACHAT-DENY: "§fAchat §cannulé§f, vous n'avez pas les §cfonds nécessaires§f. §7(§c§l%price%§7)"

FARMZONE-PERM: "menosia.farmzone"
FARMZONE-WORLD: "world"
FARMZONE-POSX: 0
FARMZONE-POSY: 80
FARMZONE-POSZ: 0
FARMZONE-YAW: 0
FARMZONE-PITCH: 0

RANDOMTP-WORLD: "world"
RANDOMTP-MINX: 300 #Coordonnées de la fin de warzone
RANBDOMTP-MAXX: 5000 #Coordonnées max du rtp
RANDOMTP-MINZ: 300 #Coordonnées de la fin de warzone
RANBDOMTP-MAXZ: 5000 #Coordonnées max du rtp

INVENTORY-EVENT-NAME: "§c§lEvents"
INVENTORY-EVENT-ITEMINFOS: "BARRIER"
INVENTORY-EVENT-INFOSLORE:
  - ""
  - ""
  - ""
INVENTORY-EVENT-INFOS: "QUARTZ_BLOCK"
INVENTORY-EVENT-INFOS-NAME: "§fEvent §7: §c§lTOTEM"
INVENTORY-EVENT-LORE:
  - ""
  - ""
  - ""
INVENTORY-EVENT-TOTEM-1: "IRON_BLOCK"
INVENTORY-EVENT-TOTEM-1-NAME: "Totem 1"
INVENTORY-EVENT-TOTEM-1-LORE:
  - ""
  - ""
  - ""
INVENTORY-EVENT-TOTEM-2: "IRON_BLOCK"
INVENTORY-EVENT-TOTEM-2-NAME: "Totem 2"
INVENTORY-EVENT-TOTEM-2-LORE:
  - ""
  - ""
  - ""
INVENTORY-EVENT-TOTEM-3: "IRON_BLOCK"
INVENTORY-EVENT-TOTEM-3-NAME: "Totem 3"
INVENTORY-EVENT-TOTEM-3-LORE:
  - ""
  - ""
  - ""


NETHER-PERM: "menosia.nether"
NETHER-WORLD: "world_nther"
NETHER-POSX: 0
NETHER-POSY: 80
NETHER-POSZ: 0
NETHER-YAW: 0
NETHER-PITCH: 0

END-PERM: "menosia.end"
END-WORLD: "world_the_end"
END-POSX: 0
END-POSY: 80
END-POSZ: 0
END-YAW: 0
END-PITCH: 0

MINAGE-PERM: "menosia.minage"
MINAGE-WORLD: "world_minage"
MINAGE-POSX: 0
MINAGE-POSY: 80
MINAGE-POSZ: 0
MINAGE-YAW: 0
MINAGE-PITCH: 0

SIGN-SHOP-TITLE: "[SHOP]"
# [SHOP]
# ITEM (ex : DIAMOND_BLOCK)
# 1000 (Prix en points)
# QUANTITY (1 par exemple)
